# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ master, beta, feature/typed-sdk ]
  pull_request:
    branches: [ master, beta, feature/typed-sdk ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: CI/CD ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm i aws-sdk@^2.581.0
    - run: npm run compile --if-present
    - run: npm run coverage-all --if-present
    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage-${{ matrix.node-version }}
        path: coverage/
