# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish Beta Package

on:
  release:
    types: [ created ]
    branches: [ beta ]

jobs:
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm i aws-sdk@^2.581.0
      - run: npm run compile --if-present
      - run: npm run coverage-all
      #- run: npm version prerelease --preid=beta-test
      - run: git push
      - run: echo ${{github.ref}}
      - run: echo beta release
      #- run: npm publish --tag beta-test
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
